<a href="https://colab.research.google.com/github/DrStephPowers/BIA/blob/main/Ch5_DataVisualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 #### <p style="background-color: #EDE7F6;color:#6600ff;display: inline-block;padding:.6rem;border-radius:.5rem">Import libraries</p>

In [2]:
import numpy as np
import pandas as pd
import warnings

 #### <p style="background-color: #EDE7F6;color:#6600ff;display: inline-block;padding:.6rem;border-radius:.5rem">Settings</p>

In [3]:
pd.options.display.max_rows = 100
pd.options.display.max_columns = 100
pd.options.display.max_colwidth = 1000
# pd.options.display.precision = 5
warnings.filterwarnings('ignore')

 #### <p style="background-color: #EDE7F6;color:#6600ff;display: inline-block;padding:.6rem;border-radius:.5rem">Import data files</p>

In [4]:
application_train = pd.read_csv("application_test.csv", index_col='SK_ID_CURR')

In [10]:
application_train.apply(lambda col: ', '.join(map(str, col.unique())))

NAME_CONTRACT_TYPE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Cash loans, Revolving loans
CODE_GENDER                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        F, M
FLAG_OWN_CAR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       N, Y
FLAG_OWN_REALTY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Y, N
CNT_CHILDREN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0, 2, 1, 3, 8, 4, 6, 5, 7, 20, 11
AMT_INCOME_TOTAL                135000.0, 99000.0, 202500.0, 315000.0, 180000.0, 270000.0, 166500.0, 162000.0, 67500.0, 247500.0, 90000.0, 225000.0, 175500.0, 157500.0, 337500.0, 76500.0, 112500.0, 360000.0, 102150.0, 171000.0, 121500.0, 405000.0, 211500.0, 229500.0, 144000.0, 40500.0, 92250.0, 279000.0, 87750.0, 126000.0, 45000.0, 252000.0, 495000.0, 189000.0, 333000.0, 81000.0, 193500.0, 63000.0, 94500.0, 292500.0, 198000.0, 216000.0, 540000.0, 450000.0, 103500.0, 206100.0, 153747.0, 117000.0, 58500.0, 234000.0, 675000.0, 261000.0, 72000.0, 382500.0, 148500.0, 301500.0, 54000.0, 56700.0, 108000.0, 288000.0, 85500.0, 153000.0, 387000.0, 57150.0, 207000.0, 254700.0, 36000.0, 47250.0, 187398.0, 130500.0, 306000.0, 139500.0, 74250.0, 607500.0, 265500.0, 256500.0, 1350000.0, 220500.0, 432000.0, 101250.0, 274500.0, 378000.0, 324000.0, 78750.0, 297000.0, 83250.0, 217350.0, 51750.0, 97920.0, 441000.0, 161550.0, 168750.0, 136170.0, 135931.5, 32850.0, 110250.0, 567000.0, 218250.0, 51300.0, 191250.0, 472500.0, 342000.0, 3...
AMT_CREDIT                      568800.0, 222768.0, 663264.0, 1575000.0, 625500.0, 959688.0, 499221.0, 180000.0, 364896.0, 45000.0, 675000.0, 261621.0, 296280.0, 360000.0, 157500.0, 407520.0, 431280.0, 478498.5, 225000.0, 266652.0, 540000.0, 1313212.5, 539100.0, 256032.0, 501363.0, 450000.0, 945000.0, 490374.0, 335592.0, 819792.0, 119925.0, 1800000.0, 513040.5, 247500.0, 463500.0, 792162.0, 729792.0, 798777.0, 261000.0, 544500.0, 207396.0, 1024740.0, 2013840.0, 869049.0, 315000.0, 1125000.0, 300735.0, 278505.0, 594121.5, 130320.0, 90000.0, 261801.0, 1907010.0, 405000.0, 630000.0, 156384.0, 981360.0, 269982.0, 165915.0, 67500.0, 312768.0, 400392.0, 328405.5, 831730.5, 526491.0, 481176.0, 781920.0, 111384.0, 735579.0, 402214.5, 323460.0, 1525482.0, 900000.0, 691551.0, 364500.0, 224149.5, 571486.5, 136287.0, 697500.0, 1096020.0, 276277.5, 1055655.0, 585000.0, 625536.0, 234576.0, 720000.0, 118512.0, 260640.0, 573408.0, 202500.0, 599778.0, 500490.0, 199152.0, 601470.0, 257391.0, 497520.0, 332946.0, 582804.0, 375408.0,...
AMT_ANNUITY                     20560.5, 17370.0, 69777.0, 49018.5, 32067.0, 34600.5, 22117.5, 14220.0, 28957.5, 5337.0, 25447.5, 16848.0, 23539.5, 18535.5, 7875.0, 21690.0, 26041.5, 23526.0, 46741.5, 19242.0, 16443.0, 27702.0, 42493.5, 29245.5, 12334.5, 10759.5, 25726.5, 23107.5, 34074.0, 35811.0, 21577.5, 17797.5, 20947.5, 39568.5, 13563.0, 98770.5, 35685.0, 61015.5, 28570.5, 12766.5, 33921.0, 27652.5, 40576.5, 37390.5, 51178.5, 26874.0, 22149.0, 42268.5, 13383.0, 43546.5, 83110.5, 31342.5, 16213.5, 65313.0, 15237.0, 30465.0, 9873.0, 7110.0, 18747.0, 25578.0, 66415.5, 36747.0, 21969.0, 13815.0, 32296.5, 11821.5, 31788.0, 32170.5, 10278.0, 8140.5, 24709.5, 42174.0, 26077.5, 30006.0, 23008.5, 24525.0, 24696.0, 39924.0, 9058.5, 32400.0, 22459.5, 23134.5, 25015.5, 63085.5, 21559.5, 17905.5, 29034.0, 54769.5, 14517.0, 27229.5, 18688.5, 13221.0, 22297.5, 20637.0, 24340.5, 8847.0, 33687.0, 56092.5, 52452.0, 17784.0, 38047.5, 29997.0, 31936.5, 20263.5, 49428.0, 7218.0, 30505.5, 7573.5, 25906.5, 34596.0, 29407.5, 13068....
AMT_GOODS_PRICE                 450000.0, 180000.0, 630000.0, 1575000.0, 625500.0, 810000.0, 373500.0, 315000.0, 45000.0, 675000.0, 216000.0, 225000.0, 360000.0, 157500.0, 454500.0, 202500.0, 540000.0, 1012500.0, 418500.0, 945000.0, 400500.0, 265500.0, 720000.0, 112500.0, 1800000.0, 472500.0, 247500.0, 463500.0, 697500.0, 261000.0, 544500.0, 900000.0, 733500.0, 1125000.0, 243000.0, 211500.0, 90000.0, 234000.0, 1741500.0, 405000.0, 135000.0, 238500.0, 126000.0, 67500.0, 270000.0, 283500.0, 702000.0, 585000.0, 328500.0, 1363500.0, 364500.0, 193500.0, 103500.0, 891000.0, 495000.0, 477000.0, 297000.0, 301500.0, 562500.0, 186700.5, 612000.0, 252000.0, 306000.0, 292500.0, 171000.0, 1350000.0, 81000.0, 378000.0, 207000.0, 1035000.0, 166500.0, 189000.0, 1080000.0, 58500.0, 346500.0, 382500.0, 351000.0, 670500.0, 819000.0, 904500.0, 117000.0, 1354500.0, 148500.0, 990000.0, 76500.0, 337500.0, 196366.5, 558000.0, 787500.0, 567000.0, 1557000.0, 441000.0, 162000.0, 139500.0, 459000.0, 594000.0, 778500.0, 369000.0, 342000.0, 2...
NAME_TYPE_SUITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Unaccompanied, nan, Family, Spouse, partner, Group of people, Other_B, Children, Other_A
NAME_INCOME_TYPE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Working, State servant, Pensioner, Commercial associate, Businessman, Student, Unemployed
NAME_EDUCATION_TYPE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Higher education, Secondary / secondary special, Incomplete higher, Lower secondary, Academic degree
NAME_FAMILY_STATUS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Married, Single / not married, Civil marriage, Widow, Separated
NAME_HOUSING_TYPE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             House / apartment, With parents, Rented apartment, Municipal apartment, Office apartment, Co-op apartment
REGION_POPULATION_RELATIVE                                                                                0.01885, 0.035792, 0.019101, 0.026392, 0.010032, 0.025164, 0.0228, 0.005144, 0.04622, 0.018634, 0.0031219999999999, 0.008019, 0.0145199999999999, 0.031329, 0.032561, 0.00702, 0.010147, 0.0072739999999999, 0.0116569999999999, 0.072508, 0.02461, 0.010966, 0.0196889999999999, 0.005002, 0.030755, 0.00496, 0.015221, 0.016612, 0.018209, 0.009175, 0.020713, 0.0084739999999999, 0.018029, 0.028663, 0.006629, 0.010276, 0.0105, 0.018801, 0.003069, 0.0060079999999999, 0.007114, 0.0038179999999999, 0.00963, 0.009334, 0.020246, 0.010556, 0.010643, 0.010006, 0.007305, 0.022625, 0.00733, 0.006233, 0.008068, 0.0088659999999999, 0.002134, 0.002042, 0.009549, 0.011703, 0.0066709999999999, 0.006852, 0.014464, 0.008625, 0.006296, 0.006207, 0.001276, 0.005313, 0.00823, 0.005084, 0.008575, 0.0035409999999999, 0.00712, 0.006305, 0.002506, 0.004849, 0.0096569999999999, 0.003813, 0.001417, 0.001333, 0.000533, 0.000938, 0.0002529999999999
DAYS_BIRTH                      -19241, -18064, -20038, -13976, -13040, -18604, -16685, -9516, -12744, -10395, -23670, -15524, -12278, -19687, -12091, -13563, -19375, -22705, -10962, -17955, -10507, -22557, -22784, -11948, -13172, -15394, -21150, -21040, -15773, -17796, -12994, -14445, -9187, -13365, -15631, -10125, -23139, -10834, -14342, -8743, -17709, -23313, -13900, -17884, -18928, -18552, -19840, -11746, -11991, -12567, -13622, -20520, -14343, -16462, -18292, -14901, -10711, -9731, -13188, -10015, -21556, -22995, -22986, -15358, -21975, -10476, -15070, -23681, -15265, -23982, -20537, -11611, -11604, -11819, -10018, -15253, -16659, -21128, -10310, -17088, -22580, -12133, -15322, -10470, -12104, -14806, -13444, -8839, -16107, -15974, -10302, -10426, -11000, -8842, -14469, -20762, -11477, -19434, -19467, -17376, -11053, -14590, -8819, -12257, -12220, -12775, -15444, -16262, -11880, -14328, -20549, -13150, -11095, -12329, -23740, -10752, -20845, -11788, -21533, -18559, -19418, -8699, -16489, -10827, -11854, -102...
DAYS_EMPLOYED                   -2329, -4469, -4458, -1866, -2191, -12009, -2580, -1387, -1013, -2625, 365243, -3555, -929, -3578, -1830, -1007, -4739, -1883, -305, -2780, -13294, -1415, -3518, -967, -2467, -1310, -2785, -2055, -1751, -270, -1397, -3060, -1161, -1787, -976, -253, -3910, -2292, -2634, -1555, -2425, -3761, -1804, -1303, -5041, -993, -3794, -2682, -2757, -1203, -6438, -1327, -126, -1283, -2062, -3235, -1083, -2786, -1169, -1685, -2117, -3552, -2612, -464, -6186, -243, -968, -1727, -291, -534, -3064, -4358, -620, -1659, -148, -9070, -472, -615, -666, -2266, -839, -4949, -3960, -2087, -553, -3254, -2924, -1372, -3714, -852, -1234, -2825, -2389, -466, -8135, -1570, -936, -1586, -338, -754, -759, -2797, -3394, -569, -1334, -777, -2576, -2646, -2513, -2774, -711, -1328, -124, -1456, -4677, -5644, -3546, -2790, -496, -2632, -249, -1009, -820, -503, -6144, -2739, -1233, -765, -2603, -2812, -4870, -1392, -4636, -1949, -3686, -1529, -1982, -206, -3781, -1644, -8540, -2696, -2674, -970, -119, -1842, -1631, -1...
DAYS_REGISTRATION               -5170.0, -9118.0, -2175.0, -2000.0, -4000.0, -6116.0, -10125.0, -5063.0, -1686.0, -8124.0, -7490.0, -7833.0, -6031.0, -10673.0, -1042.0, -5719.0, -3035.0, -5107.0, -99.0, -10087.0, -5072.0, -13154.0, -5103.0, -5611.0, -6207.0, -5389.0, -4157.0, -918.0, -7173.0, -2296.0, -164.0, -2204.0, -3663.0, -5725.0, -1545.0, -239.0, -262.0, -4039.0, -2238.0, -8712.0, -9194.0, -1806.0, -308.0, -7177.0, -6615.0, -3294.0, -1325.0, -1095.0, -5282.0, -4640.0, -5684.0, -3157.0, -6069.0, -4150.0, -4513.0, -3513.0, -14.0, -5251.0, -7143.0, -4322.0, -4896.0, -10775.0, -8014.0, -7912.0, -12431.0, -725.0, -6699.0, -3536.0, -231.0, -3369.0, -168.0, -4930.0, -5576.0, -9781.0, -4394.0, -5.0, -2132.0, -455.0, -1625.0, -10415.0, -1595.0, -6212.0, -209.0, -4531.0, -5809.0, -489.0, -2988.0, -8210.0, -8068.0, -5283.0, -1956.0, -1580.0, -5278.0, -4283.0, -661.0, -12743.0, -610.0, -9402.0, -445.0, -1477.0, -891.0, -4701.0, -2751.0, -6307.0, -583.0, -11075.0, -13476.0, -4828.0, -113.0, -2754.0, -13202.0, -2896.0, -...
DAYS_ID_PUBLISH                 -812, -1623, -3503, -4208, -4262, -2027, -241, -2055, -3171, -3041, -4136, -3985, -4586, -3183, -4221, -4044, -2895, -5990, -1721, -1516, -2729, -4187, -5229, -4052, -4243, -5433, -4658, -3663, -5049, -1224, -3461, -725, -5788, -3162, -2335, -4637, -365, -1168, -1416, -1265, -5207, -5677, -1057, -2457, -2096, -3323, -2911, -936, -4565, -2089, -4057, -797, -9, -1807, -4258, -1272, -2314, -1257, -2694, -5008, -3516, -4415, -4830, -4962, -3136, -4110, -4863, -2295, -4340, -1477, -4033, -4239, -4134, -2671, -5219, -186, -4284, -2079, -637, -3913, -3643, -5600, -3055, -1419, -3039, -4436, -1503, -2972, -5319, -2705, -20, -3680, -1485, -5678, -4165, -713, -2908, -2701, -909, -3299, -4743, -1476, -4872, -2296, -715, -2598, -2660, -3866, -2777, -2610, -4162, -3590, -4710, -4851, -432, -4163, -2234, -5090, -1649, -2941, -1373, -27, -2677, -4306, -641, -3799, -3123, -3492, -3032, -192, -1042, -3379, -3612, -5096, -4313, -569, -4630, -4256, -1913, -3206, -4904, -3729, -1243, -4287, -2178, -83...

### <p style="background-color: #EDE7F6; color: #6600ff;margin:0; display:inline-block;padding:.6rem;border-radius:.25rem;">I.DATA PREPARATION</p>

In [11]:
import sys
print(f'Original Memory Usage: {round(sys.getsizeof(application_test) / (1024 * 1024), 2)} gb.')

Original Memory Usage: 84.73 gb.

In [13]:
application_train.head(3)

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.018850,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.159520,0.066,0.059,0.9732,NaN,NaN,NaN,0.1379,0.125,NaN,NaN,NaN,0.0505,NaN,NaN,0.0672,0.0612,0.9732,NaN,NaN,NaN,0.1379,0.125,NaN,NaN,NaN,0.0526,NaN,NaN,0.0666,0.059,0.9732,NaN,NaN,NaN,0.1379,0.125,NaN,NaN,NaN,0.0514,NaN,NaN,NaN,block of flats,0.0392,"Stone, brick",No,0.0,0.0,0.0,0.0,-1740.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.035792,-18064,-4469,-9118.0,-1623,NaN,1,1,0,1,0,0,Low-skill Laborers,2.0,2,2,FRIDAY,9,0,0,0,0,0,0,Self-employed,0.564990,0.291656,0.432962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,NaN,Working,Higher education,Married,House / apartment,0.019101,-20038,-4458,-2175.0,-3503,5.0,1,1,0,1,0,0,Drivers,2.0,2,2,MONDAY,14,0,0,0,0,0,0,Transport: type 3,NaN,0.699787,0.610991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-856.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0

In [191]:
application_test = pd.read_csv("application_test.csv")
application_train = pd.read_csv("application_train.csv")
bureau = pd.read_csv("bureau.csv")
bureau_balance = pd.read_csv("bureau_balance.csv")
credit_card_balance = pd.read_csv("credit_card_balance.csv")
installments_payments = pd.read_csv("installments_payments.csv")
POS_CASH_balance = pd.read_csv("POS_CASH_balance.csv")
previous_application =  pd.read_csv("previous_application.csv")
sample_submission = pd.read_csv("sample_submission.csv")

In [4]:
application_test = pd.read_csv("application_test.csv", nrows=10000)
application_train = pd.read_csv("application_train.csv", nrows=10000)
bureau = pd.read_csv("bureau.csv", nrows=10000)
bureau_balance = pd.read_csv("bureau_balance.csv", nrows=10000)
credit_card_balance = pd.read_csv("credit_card_balance.csv", nrows=10000)
installments_payments = pd.read_csv("installments_payments.csv", nrows=10000)
POS_CASH_balance = pd.read_csv("POS_CASH_balance.csv", nrows=10000)
previous_application =  pd.read_csv("previous_application.csv", nrows=10000)
sample_submission = pd.read_csv("sample_submission.csv", nrows=10000)

### <p style="background-color: #EDE7F6; color: #6600ff;margin:0; display:inline-block;padding:.6rem;border-radius:.25rem;">Convert Types</p>

In [175]:
application_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48744 entries, 100001 to 456250
Columns: 120 entries, NAME_CONTRACT_TYPE to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: bool(5), category(11), float16(65), int16(39)
memory usage: 10.8 MB

In [190]:
x = [i for i in application_test.columns if 
     application_test[i].dtype =='int64']
x

['SK_ID_CURR',
 'CNT_CHILDREN',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_ID_PUBLISH',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21']

In [17]:
application_test['FLAG_MOBIL'].unique()

array([1, 0], dtype=int64)

In [25]:
object_to_boolen = [i for i in application_test.columns if 
                    application_test[i].nunique() < 3 and
                    application_test[i].dtype =='object' or 
                    application_test[i].dtype =='int64']
object_to_boolen

['NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_ID_PUBLISH',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'EMERGENCYSTATE_MODE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21']

In [178]:
object_to_boolen = [i for i in application_test.columns if 
                    application_test[i].nunique() < 3 and
                    application_test[i].dtype =='object']

object_to_categorical = [i for i in application_test.columns if
                         application_test[i].nunique() >=3 and
                         application_test[i].dtype =='object']

numerical_int = application_test.select_dtypes(include=['int64'])

numerical_float = application_test.select_dtypes(include=['float64'])


categorical_dummies = [i for i in application_test.columns if
                       application_test[i].nunique() >=3 and
                       application_test[i].nunique() <10 and
                       application_test[i].dtype =='object']

 #### <p style="background-color: #EDE7F6;color:#6600ff;display: inline-block;padding:.6rem;border-radius:.5rem">Missing Values</p>

In [180]:
application_test.isnull().sum()

NAME_CONTRACT_TYPE                  0
CODE_GENDER                         0
FLAG_OWN_CAR                        0
FLAG_OWN_REALTY                     0
CNT_CHILDREN                        0
AMT_INCOME_TOTAL                    0
AMT_CREDIT                          0
AMT_ANNUITY                        24
AMT_GOODS_PRICE                     0
NAME_TYPE_SUITE                   911
NAME_INCOME_TYPE                    0
NAME_EDUCATION_TYPE                 0
NAME_FAMILY_STATUS                  0
NAME_HOUSING_TYPE                   0
REGION_POPULATION_RELATIVE          0
DAYS_BIRTH                          0
DAYS_EMPLOYED                       0
DAYS_REGISTRATION                   0
DAYS_ID_PUBLISH                     0
OWN_CAR_AGE                     32312
FLAG_MOBIL                          0
FLAG_EMP_PHONE                      0
FLAG_WORK_PHONE                     0
FLAG_CONT_MOBILE                    0
FLAG_PHONE                          0
FLAG_EMAIL                          0
OCCUPATION_TYPE                 15605
CNT_FAM_MEMBERS                     0
REGION_RATING_CLIENT                0
REGION_RATING_CLIENT_W_CITY         0
WEEKDAY_APPR_PROCESS_START          0
HOUR_APPR_PROCESS_START             0
REG_REGION_NOT_LIVE_REGION          0
REG_REGION_NOT_WORK_REGION          0
LIVE_REGION_NOT_WORK_REGION         0
REG_CITY_NOT_LIVE_CITY              0
REG_CITY_NOT_WORK_CITY              0
LIVE_CITY_NOT_WORK_CITY             0
ORGANIZATION_TYPE                   0
EXT_SOURCE_1                    20532
EXT_SOURCE_2                        8
EXT_SOURCE_3                     8668
APARTMENTS_AVG                  23887
BASEMENTAREA_AVG                27641
YEARS_BEGINEXPLUATATION_AVG     22856
YEARS_BUILD_AVG                 31818
COMMONAREA_AVG                  33495
ELEVATORS_AVG                   25189
ENTRANCES_AVG                   23579
FLOORSMAX_AVG                   23321
FLOORSMIN_AVG                   32466
LANDAREA_AVG                    28254
LIVINGAPARTMENTS_AVG            32780
LIVINGAREA_AVG                  23552
NONLIVINGAPARTMENTS_AVG         33347
NONLIVINGAREA_AVG               26084
APARTMENTS_MODE                 23887
BASEMENTAREA_MODE               27641
YEARS_BEGINEXPLUATATION_MODE    22856
YEARS_BUILD_MODE                31818
COMMONAREA_MODE                 33495
ELEVATORS_MODE                  25189
ENTRANCES_MODE                  23579
FLOORSMAX_MODE                  23321
FLOORSMIN_MODE                  32466
LANDAREA_MODE                   28254
LIVINGAPARTMENTS_MODE           32780
LIVINGAREA_MODE                 23552
NONLIVINGAPARTMENTS_MODE        33347
NONLIVINGAREA_MODE              26084
APARTMENTS_MEDI                 23887
BASEMENTAREA_MEDI               27641
YEARS_BEGINEXPLUATATION_MEDI    22856
YEARS_BUILD_MEDI                31818
COMMONAREA_MEDI                 33495
ELEVATORS_MEDI                  25189
ENTRANCES_MEDI                  23579
FLOORSMAX_MEDI                  23321
FLOORSMIN_MEDI                  32466
LANDAREA_MEDI                   28254
LIVINGAPARTMENTS_MEDI           32780
LIVINGAREA_MEDI                 23552
NONLIVINGAPARTMENTS_MEDI        33347
NONLIVINGAREA_MEDI              26084
FONDKAPREMONT_MODE              32797
HOUSETYPE_MODE                  23619
TOTALAREA_MODE                  22624
WALLSMATERIAL_MODE              23893
EMERGENCYSTATE_MODE             22209
OBS_30_CNT_SOCIAL_CIRCLE           29
DEF_30_CNT_SOCIAL_CIRCLE           29
OBS_60_CNT_SOCIAL_CIRCLE           29
DEF_60_CNT_SOCIAL_CIRCLE           29
DAYS_LAST_PHONE_CHANGE              0
FLAG_DOCUMENT_2                     0
FLAG_DOCUMENT_3                     0
FLAG_DOCUMENT_4                     0
FLAG_DOCUMENT_5                     0
FLAG_DOCUMENT_6                     0
FLAG_DOCUMENT_7                     0
FLAG_DOCUMENT_8                     0
FLAG_DOCUMENT_9                     0
FLAG_DOCUMENT_10                    0
FLAG_DOCUMENT_11                    0
FLAG_DOCUMENT_12                    0
FLAG_DOCUMENT_13                    0
FLAG_DOCUMENT_14                    0
FLAG_DOCUMENT_15                    0
FLAG_DOCUMENT_16                    0
FLAG_DOCUMENT_17                    0
FLAG_DOCUMENT_18                    0
FLAG_DOCUMENT_19                    0
FLAG_DOCUMENT_20                    0
FLAG_DOCUMENT_21                    0
AMT_REQ_CREDIT_BUREAU_HOUR       6049
AMT_REQ_CREDIT_BUREAU_DAY        6049
AMT_REQ_CREDIT_BUREAU_WEEK       6049
AMT_REQ_CREDIT_BUREAU_MON        6049
AMT_REQ_CREDIT_BUREAU_QRT        6049
AMT_REQ_CREDIT_BUREAU_YEAR       6049
dtype: int64

In [181]:
def fill_empty(df):
    for i  in df:
        df[i] = df[i].fillna(df[i].mode()[0])
    return df
application_test = fill_empty(application_test)

In [182]:
def convert_types (df):
    for i in object_to_boolen:
         df[i] = df[i].astype('bool')
    for i in object_to_categorical:
         df[i] = df[i].astype('category')
    for i in numerical_int:
         df[i] = df[i].astype('int32')  
    for i in numerical_float:
         df[i] = df[i].astype('float16') 
    return df

In [187]:
original_memory = application_test.memory_usage().sum()
original_memory

9680132

In [184]:
application_test =convert_types(application_test)

In [ ]:
application_test = convert_types(application_test)
application_train = convert_types(application_train)
bureau = convert_types(bureau)
bureau_balance = convert_types(bureau_balance)
credit_card_balance = convert_types(credit_card_balance)
installments_payments = convert_types(installments_payments)
POS_CASH_balance = convert_types(POS_CASH_balance)
previous_application =  convert_types(previous_application)
sample_submission = convert_types(sample_submission)

In [20]:
lista = [(application_test),
(application_train),
(bureau),
(bureau_balance),
(credit_card_balance),
(installments_payments),
(POS_CASH_balance),
(previous_application),
(sample_submission)]

In [6]:
a=[]
for i in lista:
    a.append(i.memory_usage().sum())
a

[9680132, 9760132, 1360132, 240132, 1840132, 640132, 640132, 2960132, 160132]

In [12]:
lista_2 = ['application_test',
'application_train',
'bureau',
'bureau_balance',
'credit_card_balance',
'installments_payments',
'POS_CASH_balance',
'previous_application',
'sample_submission']

In [19]:
mapped = zip(lista_2, a)
print(set(mapped))

{('installments_payments', 640132), ('application_train', 9760132), ('POS_CASH_balance', 640132), ('application_test', 9680132), ('sample_submission', 160132), ('bureau', 1360132), ('bureau_balance', 240132), ('credit_card_balance', 1840132), ('previous_application', 2960132)}

In [14]:
new_dict = {lista_2: a for lista_2,
            a in zip(lista_2, a)}
new_dict

{'application_test': 9680132,
 'application_train': 9760132,
 'bureau': 1360132,
 'bureau_balance': 240132,
 'credit_card_balance': 1840132,
 'installments_payments': 640132,
 'POS_CASH_balance': 640132,
 'previous_application': 2960132,
 'sample_submission': 160132}

In [27]:
for key in new_dict.keys():
    print("Key:", key, "Value:", new_dict[key])

Key: application_test Value: 9680132
Key: application_train Value: 9760132
Key: bureau Value: 1360132
Key: bureau_balance Value: 240132
Key: credit_card_balance Value: 1840132
Key: installments_payments Value: 640132
Key: POS_CASH_balance Value: 640132
Key: previous_application Value: 2960132
Key: sample_submission Value: 160132

In [30]:
for value in new_dict.values():
    print("Value:", value )

Value: 9680132
Value: 9760132
Value: 1360132
Value: 240132
Value: 1840132
Value: 640132
Value: 640132
Value: 2960132
Value: 160132

In [36]:
for i in new_dict:
    print(i,':', new_dict[i])

application_test : 9680132
application_train : 9760132
bureau : 1360132
bureau_balance : 240132
credit_card_balance : 1840132
installments_payments : 640132
POS_CASH_balance : 640132
previous_application : 2960132
sample_submission : 160132

In [38]:
for i in new_dict:
    print(i, new_dict[i], sep=': ')

application_test: 9680132
application_train: 9760132
bureau: 1360132
bureau_balance: 240132
credit_card_balance: 1840132
installments_payments: 640132
POS_CASH_balance: 640132
previous_application: 2960132
sample_submission: 160132

In [56]:
list_of_keys = list(new_dict.keys())
list_of_keys

['application_test',
 'application_train',
 'bureau',
 'bureau_balance',
 'credit_card_balance',
 'installments_payments',
 'POS_CASH_balance',
 'previous_application',
 'sample_submission']

In [58]:
'bureau' in list_of_keys

True

In [53]:
test=['application_test',
'application_train']

In [55]:
test.extend(['aaa','aa1'])
test

['application_test', 'application_train', 'aaa', 'aa1']

In [8]:
for i,col in test:
    print(f'{col}')

ValueError: too many values to unpack (expected 2)

In [313]:
print(f'{test[0]}')

application_test

In [71]:
lista = ['application_test',
       'application_train']

for i in range(len(test)):
#     before_memory = test[i].memory_usage().sum()
#     print(test[i])
    a= test[i]
    print(f'{a}')

application_test
application_train

In [70]:
for i in range(len(test)):
#     before_memory = test[i].memory_usage().sum()
#     print(test[i])
    print(f'{test[i].memory_usage().sum()}')

AttributeError: 'str' object has no attribute 'memory_usage'

In [69]:
ini_list = ['assa', 'b', 'c', 'd']
 
print (*ini_list[0], sep ='')

assa

In [83]:
lista = ['application_test',
       'application_train']

z= print(''.join(lista[0]))

application_test
None

In [86]:
lista = ['application_test',
       'application_train']
z = lista[0]
z

AttributeError: 'str' object has no attribute 'astype'

In [47]:
string = 'Geeks"-for-Geeks'
string.replace("\"", "a")

'Geeksa-for-Geeks'

In [49]:
lista = [application_test,
       application_train]
str(lista[0])

'      SK_ID_CURR NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  \\\n0         100001         Cash loans           F            N               Y   \n1         100005         Cash loans           M            N               Y   \n2         100013         Cash loans           M            Y               Y   \n3         100028         Cash loans           F            N               Y   \n4         100038         Cash loans           M            Y               N   \n...          ...                ...         ...          ...             ...   \n9995      172551         Cash loans           F            N               Y   \n9996      172556         Cash loans           M            Y               N   \n9997      172562         Cash loans           F            N               Y   \n9998      172570         Cash loans           M            N               Y   \n9999      172574         Cash loans           F            N               N   \n\n      CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \\\n0                0          135000.0    568800.0      20560.5   \n1                0           99000.0    222768.0      17370.0   \n2                0          202500.0    663264.0      69777.0   \n3                2          315000.0   1575000.0      49018.5   \n4                1          180000.0    625500.0      32067.0   \n...            ...               ...         ...          ...   \n9995             0          135000.0    454500.0      29173.5   \n9996             1          180000.0    500490.0      52555.5   \n9997             0          202500.0    523152.0      37336.5   \n9998             1          382500.0    967500.0      31338.0   \n9999             1          112500.0    539100.0      22837.5   \n\n      AMT_GOODS_PRICE NAME_TYPE_SUITE      NAME_INCOME_TYPE  \\\n0            450000.0   Unaccompanied               Working   \n1            180000.0   Unaccompanied               Working   \n2            630000.0             NaN               Working   \n3           1575000.0   Unaccompanied               Working   \n4            625500.0   Unaccompanied               Working   \n...               ...             ...                   ...   \n9995         454500.0   Unaccompanied         State servant   \n9996         450000.0   Unaccompanied  Commercial associate   \n9997         463500.0   Unaccompanied         State servant   \n9998         967500.0          Family         State servant   \n9999         450000.0   Unaccompanied  Commercial associate   \n\n                NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  \\\n0                  Higher education               Married   \n1     Secondary / secondary special               Married   \n2                  Higher education               Married   \n3     Secondary / secondary special               Married   \n4     Secondary / secondary special               Married   \n...                             ...                   ...   \n9995  Secondary / secondary special  Single / not married   \n9996  Secondary / secondary special               Married   \n9997  Secondary / secondary special                 Widow   \n9998               Higher education               Married   \n9999               Higher education               Married   \n\n        NAME_HOUSING_TYPE  REGION_POPULATION_RELATIVE  DAYS_BIRTH  \\\n0       House / apartment                    0.018850      -19241   \n1       House / apartment                    0.035792      -18064   \n2       House / apartment                    0.019101      -20038   \n3       House / apartment                    0.026392      -13976   \n4       House / apartment                    0.010032      -13040   \n...                   ...                         ...         ...   \n9995    House / apartment                    0.028663      -18338   \n9996  Municipal apartment                    0.046220      -15040   \n9997    House / apartment                    0.032561      -17225   \n9998  Municipal apartment                    0.072508      -14852   \n9999         With parents                    0.010276      -11056   \n\n      DAYS_EMPLOYED  DAYS_REGISTRATION  DAYS_ID_PUBLISH  OWN_CAR_AGE  \\\n0             -2329            -5170.0             -812          NaN   \n1             -4469            -9118.0            -1623          NaN   \n2             -4458            -2175.0            -3503          5.0   \n3             -1866            -2000.0            -4208          NaN   \n4             -2191            -4000.0            -4262         16.0   \n...             ...                ...              ...          ...   \n9995         -11264           -11220.0            -1892          NaN   \n9996          -2125            -8982.0            -4474         18.0   \n9997           -114            -1397.0             -771          NaN   \n9998           -839            -3520.0            -1753          NaN   \n9999           -142            -5187.0            -3709          NaN   \n\n      FLAG_MOBIL  FLAG_EMP_PHONE  FLAG_WORK_PHONE  FLAG_CONT_MOBILE  \\\n0              1               1                0                 1   \n1              1               1                0                 1   \n2              1               1                0                 1   \n3              1               1                0                 1   \n4              1               1                1                 1   \n...          ...             ...              ...               ...   \n9995           1               1                0                 1   \n9996           1               1                1                 1   \n9997           1               1                0                 1   \n9998           1               1                0                 1   \n9999           1               1                1                 1   \n\n      FLAG_PHONE  FLAG_EMAIL     OCCUPATION_TYPE  CNT_FAM_MEMBERS  \\\n0              0           1                 NaN              2.0   \n1              0           0  Low-skill Laborers              2.0   \n2              0           0             Drivers              2.0   \n3              1           0         Sales staff              4.0   \n4              0           0                 NaN              3.0   \n...          ...         ...                 ...              ...   \n9995           0           0      Medicine staff              1.0   \n9996           0           0            Laborers              3.0   \n9997           0           1                 NaN              1.0   \n9998           0           1            IT staff              3.0   \n9999           0           1                 NaN              3.0   \n\n      REGION_RATING_CLIENT  REGION_RATING_CLIENT_W_CITY  \\\n0                        2                            2   \n1                        2                            2   \n2                        2                            2   \n3                        2                            2   \n4                        2                            2   \n...                    ...                          ...   \n9995                     2                            2   \n9996                     1                            1   \n9997                     1                            1   \n9998                     1                            1   \n9999                     2                            2   \n\n     WEEKDAY_APPR_PROCESS_START  HOUR_APPR_PROCESS_START  \\\n0                       TUESDAY                       18   \n1                        FRIDAY                        9   \n2                        MONDAY                       14   \n3                     WEDNESDAY                       11   \n4                        FRIDAY                        5   \n...                         ...                      ...   \n9995                   THURSDAY                       13   \n9996                     FRIDAY                       19   \n9997                    TUESDAY                       12   \n9998                   THURSDAY                       16   \n9999                    TUESDAY                       13   \n\n      REG_REGION_NOT_LIVE_REGION  REG_REGION_NOT_WORK_REGION  \\\n0                              0                           0   \n1                              0                           0   \n2                              0                           0   \n3                              0                           0   \n4                              0                           0   \n...                          ...                         ...   \n9995                           0                           0   \n9996                           0                           1   \n9997                           0                           0   \n9998                           0                           0   \n9999                           0                           0   \n\n      LIVE_REGION_NOT_WORK_REGION  REG_CITY_NOT_LIVE_CITY  \\\n0                               0                       0   \n1                               0                       0   \n2                               0                       0   \n3                               0                       0   \n4                               0                       0   \n...                           ...                     ...   \n9995                            0                       0   \n9996                            1                       0   \n9997                            0                       0   \n9998                            0                       0   \n9999                            0                       0   \n\n      REG_CITY_NOT_WORK_CITY  LIVE_CITY_NOT_WORK_CITY       ORGANIZATION_TYPE  \\\n0                          0                        0            Kindergarten   \n1                          0                        0           Self-employed   \n2                          0                        0       Transport: type 3   \n3                          0                        0  Business Entity Type 3   \n4                          1                        1  Business Entity Type 3   \n...                      ...                      ...                     ...   \n9995                       0                        0                Medicine   \n9996                       1                        1                   Other   \n9997                       0                        0  Business Entity Type 3   \n9998                       0                        0              Government   \n9999                       0                        0  Business Entity Type 3   \n\n      EXT_SOURCE_1  EXT_SOURCE_2  EXT_SOURCE_3  APARTMENTS_AVG  \\\n0         0.752614      0.789654      0.159520          0.0660   \n1         0.564990      0.291656      0.432962             NaN   \n2              NaN      0.699787      0.610991             NaN   \n3         0.525734      0.509677      0.612704          0.3052   \n4         0.202145      0.425687           NaN             NaN   \n...            ...           ...           ...             ...   \n9995           NaN      0.536456      0.675413          0.0979   \n9996      0.438157      0.744736      0.352340          0.0577   \n9997           NaN      0.760022           NaN          0.1381   \n9998      0.687417      0.623376      0.243186          0.2603   \n9999      0.382110      0.737846      0.418854          0.0247   \n\n      BASEMENTAREA_AVG  YEARS_BEGINEXPLUATATION_AVG  YEARS_BUILD_AVG  \\\n0               0.0590                       0.9732              NaN   \n1                  NaN                          NaN              NaN   \n2                  NaN                          NaN              NaN   \n3               0.1974                       0.9970           0.9592   \n4                  NaN                          NaN              NaN   \n...                ...                          ...              ...   \n9995            0.0552                       0.9717              NaN   \n9996               NaN                       0.9752              NaN   \n9997            0.1397                       0.9752           0.6600   \n9998            0.1686                       0.9791           0.7144   \n9999               NaN                       0.9697           0.5784   \n\n      COMMONAREA_AVG  ELEVATORS_AVG  ENTRANCES_AVG  FLOORSMAX_AVG  \\\n0                NaN            NaN         0.1379         0.1250   \n1                NaN            NaN            NaN            NaN   \n2                NaN            NaN            NaN            NaN   \n3             0.1165           0.32         0.2759         0.3750   \n4                NaN            NaN            NaN            NaN   \n...              ...            ...            ...            ...   \n9995             NaN           0.00         0.0690         0.1667   \n9996             NaN            NaN         0.1034         0.1667   \n9997             NaN           0.00         0.3103         0.1667   \n9998          0.0382           0.28         0.2414         0.3333   \n9999             NaN           0.00         0.0862         0.0625   \n\n      FLOORSMIN_AVG  LANDAREA_AVG  LIVINGAPARTMENTS_AVG  LIVINGAREA_AVG  \\\n0               NaN           NaN                   NaN          0.0505   \n1               NaN           NaN                   NaN             NaN   \n2               NaN           NaN                   NaN             NaN   \n3            0.0417        0.2042                0.2404          0.3673   \n4               NaN           NaN                   NaN             NaN   \n...             ...           ...                   ...             ...   \n9995            NaN           NaN                   NaN          0.0987   \n9996            NaN           NaN                   NaN          0.0305   \n9997         0.2083        0.0257                   NaN          0.1205   \n9998         0.3750        0.0000                0.2110          0.2459   \n9999         0.1250        0.0318                0.0303          0.0307   \n\n      NONLIVINGAPARTMENTS_AVG  NONLIVINGAREA_AVG  APARTMENTS_MODE  \\\n0                         NaN                NaN           0.0672   \n1                         NaN                NaN              NaN   \n2                         NaN                NaN              NaN   \n3                      0.0386             0.0800           0.3109   \n4                         NaN                NaN              NaN   \n...                       ...                ...              ...   \n9995                      NaN             0.1145           0.0998   \n9996                      NaN             0.0104           0.0588   \n9997                      NaN             0.0039           0.1408   \n9998                   0.0058             0.0064           0.1523   \n9999                      NaN             0.0000           0.0126   \n\n      BASEMENTAREA_MODE  YEARS_BEGINEXPLUATATION_MODE  YEARS_BUILD_MODE  \\\n0                0.0612                        0.9732               NaN   \n1                   NaN                           NaN               NaN   \n2                   NaN                           NaN               NaN   \n3                0.2049                        0.9970            0.9608   \n4                   NaN                           NaN               NaN   \n...                 ...                           ...               ...   \n9995             0.0573                        0.9717               NaN   \n9996                NaN                        0.9752               NaN   \n9997             0.1450                        0.9752            0.6733   \n9998             0.1036                        0.9791            0.7256   \n9999                NaN                        0.9692            0.5949   \n\n      COMMONAREA_MODE  ELEVATORS_MODE  ENTRANCES_MODE  FLOORSMAX_MODE  \\\n0                 NaN             NaN          0.1379          0.1250   \n1                 NaN             NaN             NaN             NaN   \n2                 NaN             NaN             NaN             NaN   \n3              0.1176          0.3222          0.2759          0.3750   \n4                 NaN             NaN             NaN             NaN   \n...               ...             ...             ...             ...   \n9995              NaN          0.0000          0.0690          0.1667   \n9996              NaN             NaN          0.1034          0.1667   \n9997              NaN          0.0000          0.3103          0.1667   \n9998           0.0210          0.1611          0.1379          0.3333   \n9999              NaN          0.0000          0.0690          0.0417   \n\n      FLOORSMIN_MODE  LANDAREA_MODE  LIVINGAPARTMENTS_MODE  LIVINGAREA_MODE  \\\n0                NaN            NaN                    NaN           0.0526   \n1                NaN            NaN                    NaN              NaN   \n2                NaN            NaN                    NaN              NaN   \n3             0.0417         0.2089                 0.2626           0.3827   \n4                NaN            NaN                    NaN              NaN   \n...              ...            ...                    ...              ...   \n9995             NaN            NaN                    NaN           0.1028   \n9996             NaN            NaN                    NaN           0.0318   \n9997          0.2083         0.0263                    NaN           0.1256   \n9998          0.3750         0.0000                 0.1322           0.1473   \n9999          0.1250         0.0279                 0.0331           0.0185   \n\n      NONLIVINGAPARTMENTS_MODE  NONLIVINGAREA_MODE  APARTMENTS_MEDI  \\\n0                          NaN                 NaN           0.0666   \n1                          NaN                 NaN              NaN   \n2                          NaN                 NaN              NaN   \n3                       0.0389              0.0847           0.3081   \n4                          NaN                 NaN              NaN   \n...                        ...                 ...              ...   \n9995                       NaN              0.1212           0.0989   \n9996                       NaN              0.0110           0.0583   \n9997                       NaN              0.0041           0.1395   \n9998                    0.0039              0.0001           0.2628   \n9999                       NaN              0.0000           0.0250   \n\n      BASEMENTAREA_MEDI  YEARS_BEGINEXPLUATATION_MEDI  YEARS_BUILD_MEDI  \\\n0                0.0590                        0.9732               NaN   \n1                   NaN                           NaN               NaN   \n2                   NaN                           NaN               NaN   \n3                0.1974                        0.9970            0.9597   \n4                   NaN                           NaN               NaN   \n...                 ...                           ...               ...   \n9995             0.0552                        0.9717               NaN   \n9996                NaN                        0.9752               NaN   \n9997             0.1397                        0.9752            0.6645   \n9998             0.1686                        0.9791            0.7182   \n9999                NaN                        0.9697            0.5840   \n\n      COMMONAREA_MEDI  ELEVATORS_MEDI  ENTRANCES_MEDI  FLOORSMAX_MEDI  \\\n0                 NaN             NaN          0.1379          0.1250   \n1                 NaN             NaN             NaN             NaN   \n2                 NaN             NaN             NaN             NaN   \n3              0.1173            0.32          0.2759          0.3750   \n4                 NaN             NaN             NaN             NaN   \n...               ...

In [55]:
ini_list = ['a', 'b', 'c', 'd']

print (*ini_list[0], sep =', ')

a

In [31]:
a='as_we'
lista = ['application_test',
       'application_train']
out = a.strip('_') 
out
lista[0]

SyntaxError: can't use starred expression here (2081758780.py, line 6)

In [23]:
 lista = ['application_test',
       'application_train']

out = {}   
for i, col in enumerate(lista):
    out[col] = lista[i].strip('_')
print(out)

{'application_test': 'application_test', 'application_train': 'application_train'}

In [185]:
after_memory = application_test.memory_usage().sum()
after_memory

15116312

In [173]:
application_test.head(5)

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100001,True,True,True,True,0,inf,inf,20560.0,inf,Unaccompanied,Working,Higher education,Married,House / apartment,0.018845,-19241,-2329,-5168.0,-812,4.0,1,1,0,1,0,1,Laborers,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752441,0.789551,0.159546,0.065979,0.058990,0.973145,0.823242,0.000000,0.000000,0.137939,0.125000,0.208252,0.000000,0.067200,0.050507,0.000000,0.000000,0.067200,0.061188,0.973145,0.830078,0.000000,0.000000,0.137939,0.125000,0.208252,0.000000,0.073486,0.052612,0.00000,0.000000,0.066589,0.058990,0.973145,0.825684,0.00000,0.000000,0.137939,0.125000,0.208252,0.000000,0.068420,0.051392,0.000000,0.000000,reg oper account,block of flats,0.039215,"Stone, brick",True,0.0,0.0,0.0,0.0,-1740.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100005,True,True,True,True,0,inf,inf,17376.0,inf,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.035797,-18064,-4469,-9120.0,-1623,4.0,1,1,0,1,0,0,Low-skill Laborers,2.0,2,2,FRIDAY,9,0,0,0,0,0,0,Self-employed,0.564941,0.291748,0.432861,0.082520,0.000000,0.986816,0.823242,0.000000,0.000000,0.137939,0.166748,0.208252,0.000000,0.067200,0.000000,0.000000,0.000000,0.083984,0.000000,0.986816,0.830078,0.000000,0.000000,0.137939,0.166748,0.208252,0.000000,0.073486,0.000000,0.00000,0.000000,0.083313,0.000000,0.986816,0.825684,0.00000,0.000000,0.137939,0.166748,0.208252,0.000000,0.068420,0.000000,0.000000,0.000000,reg oper account,block of flats,0.000000,Panel,True,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
100013,True,True,True,True,0,inf,inf,inf,inf,Unaccompanied,Working,Higher education,Married,House / apartment,0.019104,-20038,-4458,-2176.0,-3503,5.0,1,1,0,1,0,0,Drivers,2.0,2,2,MONDAY,14,0,0,0,0,0,0,Transport: type 3,0.377686,0.699707,0.610840,0.082520,0.000000,0.986816,0.823242,0.000000,0.000000,0.137939,0.166748,0.208252,0.000000,0.067200,0.000000,0.000000,0.000000,0.083984,0.000000,0.986816,0.830078,0.000000,0.000000,0.137939,0.166748,0.208252,0.000000,0.073486,0.000000,0.00000,0.000000,0.083313,0.000000,0.986816,0.825684,0.00000,0.000000,0.137939,0.166748,0.208252,0.000000,0.068420,0.000000,0.000000,0.000000,reg oper account,block of flats,0.000000,Panel,True,0.0,0.0,0.0,0.0,-856.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
100028,True,True,True,True,2,inf,inf,49024.0,inf,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.026398,-13976,-1866,-2000.0,-4208,4.0,1,1,0,1,1,0,Sales staff,4.0,2,2,WEDNESDAY,11,0,0,0,0,0,0,Business Entity Type 3,0.525879,0.509766,0.612793,0.305176,0.197388,0.997070,0.958984,0.116516,0.320068,0.275879,0.375000,0.041687,0.204224,0.240356,0.367188,0.038605,0.080017,0.310791,0.204956,0.997070,0.960938,0.117615,0.322266,0.275879,0.375000,0.041687,0.208862,0.262695,0.382812,0.03891,0.084717,0.308105,0.197388,0.997070,0.959473,0.11731,0.320068,0.275879,0.375000,0.041687,0.207764,0.244629,0.373779,0.038788,0.081726,reg oper account,block of flats,0.370117,Panel,True,0.0,0.0,0.0,0.0,-1805.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
100038,True,True,True,True,1,inf,inf,32064.0,inf,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.010033,-13040,-2191,-4000.0,-4262,16.0,1,1,1,1,0,0,Laborers,3.0,2,2,FRIDAY,5,0,0,0,0,1,1,Business Entity Type 3,0.202148,0.425781,0.706055,0.082520,0.000000,0.986816,0.823242,0.000000,0.000000,0.137939,0.166748,0.208252,0.000000,0.067200,0.000000,0.000000,0.000000,0.083984,0.000000,0.986816,0.830078,0.000000,0.000000,0.137939,0.166748,0.208252,0.000000,0.073486,0.000000,0.00000,0.000000,0.083313,0.000000,0.986816,0.825684,0.00000,0.000000,0.137939,0.166748,0.208252,0.000000,0.068420,0.000000,0.000000,0.000000,reg oper account,block of flats,0.000000,Panel,True,0.0,0.0,0.0,0.0,-821.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
application_test_2 = application_test.head(1000)

In [24]:
application_test_2.sort_values('SK_ID_CURR').head(5)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,...,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.018850,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.159520,0.0660,0.0590,0.9732,NaN,NaN,NaN,0.1379,...,0.0666,0.0590,0.9732,NaN,NaN,NaN,0.1379,0.125,NaN,NaN,NaN,0.0514,NaN,NaN,NaN,block of flats,0.0392,"Stone, brick",No,0.0,0.0,0.0,0.0,-1740.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.035792,-18064,-4469,-9118.0,-1623,NaN,1,1,0,1,0,0,Low-skill Laborers,2.0,2,2,FRIDAY,9,0,0,0,0,0,0,Self-employed,0.564990,0.291656,0.432962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,NaN,Working,Higher education,Married,House / apartment,0.019101,-20038,-4458,-2175.0,-3503,5.0,1,1,0,1,0,0,Drivers,2.0,2,2,MONDAY,14,0,0,0,0,0,0,Transport: type 3,NaN,0.699787,0.610991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-856.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.026392,-13976,-1866,-2000.0,-4208,NaN,1,1,0,1,1,0,Sales staff,4.0,2,2,WEDNESDAY,11,0,0,0,0,0,0,Business Entity Type 3,0.525734,0.509677,0.612704,0.3052,0.1974,0.9970,0.9592,0.1165,0.32,0.2759,...,0.3081,0.1974,0.9970,0.9597,0.1173,0.32,0.2759,0.375,0.0417,0.2078,0.2446,0.3739,0.0388,0.0817,reg oper account,block of flats,0.3700,Panel,No,0.0,0.0,0.0,0.0,-1805.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.010032,-13040,-2191,-4000.0,-4262,16.0,1,1,1,1,0,0,NaN,3.0,2,2,FRIDAY,5,0,0,0,0,1,1,Business Entity Type 3,0.202145,0.425687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-821.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
application_test_3 = application_test['SK_ID_CURR'].head(1000)

In [6]:
application_test_3.tail()

995    106851
996    106852
997    106853
998    106854
999    106861
Name: SK_ID_CURR, dtype: int64

In [7]:
zz = bureau.merge(application_test_3, how='right', on='SK_ID_CURR')

In [8]:
zz.shape

(5292, 17)

In [41]:
zz.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,100001,5896630.0,Closed,currency 1,-857.0,0.0,-492.0,-553.0,NaN,0.0,112500.0,0.0,0.0,0.0,Consumer credit,-155.0,0.0
1,100001,5896631.0,Closed,currency 1,-909.0,0.0,-179.0,-877.0,NaN,0.0,279720.0,0.0,0.0,0.0,Consumer credit,-155.0,0.0
2,100001,5896632.0,Closed,currency 1,-879.0,0.0,-514.0,-544.0,NaN,0.0,91620.0,0.0,0.0,0.0,Consumer credit,-155.0,0.0
3,100001,5896633.0,Closed,currency 1,-1572.0,0.0,-1329.0,-1328.0,NaN,0.0,85500.0,0.0,0.0,0.0,Consumer credit,-155.0,0.0
4,100001,5896634.0,Active,currency 1,-559.0,0.0,902.0,NaN,NaN,0.0,337680.0,113166.0,0.0,0.0,Consumer credit,-6.0,4630.5

In [9]:
a = pd.get_dummies(bureau_balance, columns=['MONTHS_BALANCE'])

In [31]:
a.head(4)

,SK_ID_BUREAU,STATUS,MONTHS_BALANCE_-96,MONTHS_BALANCE_-95,MONTHS_BALANCE_-94,MONTHS_BALANCE_-93,MONTHS_BALANCE_-92,MONTHS_BALANCE_-91,MONTHS_BALANCE_-90,MONTHS_BALANCE_-89,MONTHS_BALANCE_-88,MONTHS_BALANCE_-87,MONTHS_BALANCE_-86,MONTHS_BALANCE_-85,MONTHS_BALANCE_-84,MONTHS_BALANCE_-83,MONTHS_BALANCE_-82,MONTHS_BALANCE_-81,MONTHS_BALANCE_-80,MONTHS_BALANCE_-79,MONTHS_BALANCE_-78,MONTHS_BALANCE_-77,MONTHS_BALANCE_-76,MONTHS_BALANCE_-75,MONTHS_BALANCE_-74,MONTHS_BALANCE_-73,MONTHS_BALANCE_-72,MONTHS_BALANCE_-71,MONTHS_BALANCE_-70,MONTHS_BALANCE_-69,MONTHS_BALANCE_-68,MONTHS_BALANCE_-67,MONTHS_BALANCE_-66,MONTHS_BALANCE_-65,MONTHS_BALANCE_-64,MONTHS_BALANCE_-63,MONTHS_BALANCE_-62,MONTHS_BALANCE_-61,MONTHS_BALANCE_-60,MONTHS_BALANCE_-59,MONTHS_BALANCE_-58,MONTHS_BALANCE_-57,MONTHS_BALANCE_-56,MONTHS_BALANCE_-55,MONTHS_BALANCE_-54,MONTHS_BALANCE_-53,MONTHS_BALANCE_-52,MONTHS_BALANCE_-51,MONTHS_BALANCE_-50,MONTHS_BALANCE_-49,MONTHS_BALANCE_-48,MONTHS_BALANCE_-47,MONTHS_BALANCE_-46,MONTHS_BALANCE_-45,MONTHS_BALANCE_-44,MONTHS_BALANCE_-43,MONTHS_BALANCE_-42,MONTHS_BALANCE_-41,MONTHS_BALANCE_-40,MONTHS_BALANCE_-39,MONTHS_BALANCE_-38,MONTHS_BALANCE_-37,MONTHS_BALANCE_-36,MONTHS_BALANCE_-35,MONTHS_BALANCE_-34,MONTHS_BALANCE_-33,MONTHS_BALANCE_-32,MONTHS_BALANCE_-31,MONTHS_BALANCE_-30,MONTHS_BALANCE_-29,MONTHS_BALANCE_-28,MONTHS_BALANCE_-27,MONTHS_BALANCE_-26,MONTHS_BALANCE_-25,MONTHS_BALANCE_-24,MONTHS_BALANCE_-23,MONTHS_BALANCE_-22,MONTHS_BALANCE_-21,MONTHS_BALANCE_-20,MONTHS_BALANCE_-19,MONTHS_BALANCE_-18,MONTHS_BALANCE_-17,MONTHS_BALANCE_-16,MONTHS_BALANCE_-15,MONTHS_BALANCE_-14,MONTHS_BALANCE_-13,MONTHS_BALANCE_-12,MONTHS_BALANCE_-11,MONTHS_BALANCE_-10,MONTHS_BALANCE_-9,MONTHS_BALANCE_-8,MONTHS_BALANCE_-7,MONTHS_BALANCE_-6,MONTHS_BALANCE_-5,MONTHS_BALANCE_-4,MONTHS_BALANCE_-3,MONTHS_BALANCE_-2,MONTHS_BALANCE_-1,MONTHS_BALANCE_0
0,5715448,C,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,5715448,C,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,5715448,C,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3,5715448,C,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [10]:
bureau_2 = zz.merge(a, how='left', on='SK_ID_BUREAU')

In [11]:
bureau_2.shape

(192035, 115)

In [26]:
bureau_2.sort_values('SK_ID_CURR').head(5)

,SK_ID_CURR,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,STATUS,MONTHS_BALANCE_-96,MONTHS_BALANCE_-95,MONTHS_BALANCE_-94,MONTHS_BALANCE_-93,MONTHS_BALANCE_-92,MONTHS_BALANCE_-91,MONTHS_BALANCE_-90,MONTHS_BALANCE_-89,MONTHS_BALANCE_-88,MONTHS_BALANCE_-87,MONTHS_BALANCE_-86,MONTHS_BALANCE_-85,MONTHS_BALANCE_-84,MONTHS_BALANCE_-83,MONTHS_BALANCE_-82,MONTHS_BALANCE_-81,MONTHS_BALANCE_-80,MONTHS_BALANCE_-79,MONTHS_BALANCE_-78,MONTHS_BALANCE_-77,MONTHS_BALANCE_-76,MONTHS_BALANCE_-75,MONTHS_BALANCE_-74,MONTHS_BALANCE_-73,MONTHS_BALANCE_-72,MONTHS_BALANCE_-71,MONTHS_BALANCE_-70,MONTHS_BALANCE_-69,MONTHS_BALANCE_-68,MONTHS_BALANCE_-67,MONTHS_BALANCE_-66,MONTHS_BALANCE_-65,MONTHS_BALANCE_-64,...,MONTHS_BALANCE_-49,MONTHS_BALANCE_-48,MONTHS_BALANCE_-47,MONTHS_BALANCE_-46,MONTHS_BALANCE_-45,MONTHS_BALANCE_-44,MONTHS_BALANCE_-43,MONTHS_BALANCE_-42,MONTHS_BALANCE_-41,MONTHS_BALANCE_-40,MONTHS_BALANCE_-39,MONTHS_BALANCE_-38,MONTHS_BALANCE_-37,MONTHS_BALANCE_-36,MONTHS_BALANCE_-35,MONTHS_BALANCE_-34,MONTHS_BALANCE_-33,MONTHS_BALANCE_-32,MONTHS_BALANCE_-31,MONTHS_BALANCE_-30,MONTHS_BALANCE_-29,MONTHS_BALANCE_-28,MONTHS_BALANCE_-27,MONTHS_BALANCE_-26,MONTHS_BALANCE_-25,MONTHS_BALANCE_-24,MONTHS_BALANCE_-23,MONTHS_BALANCE_-22,MONTHS_BALANCE_-21,MONTHS_BALANCE_-20,MONTHS_BALANCE_-19,MONTHS_BALANCE_-18,MONTHS_BALANCE_-17,MONTHS_BALANCE_-16,MONTHS_BALANCE_-15,MONTHS_BALANCE_-14,MONTHS_BALANCE_-13,MONTHS_BALANCE_-12,MONTHS_BALANCE_-11,MONTHS_BALANCE_-10,MONTHS_BALANCE_-9,MONTHS_BALANCE_-8,MONTHS_BALANCE_-7,MONTHS_BALANCE_-6,MONTHS_BALANCE_-5,MONTHS_BALANCE_-4,MONTHS_BALANCE_-3,MONTHS_BALANCE_-2,MONTHS_BALANCE_-1,MONTHS_BALANCE_0
0,100001,Closed,currency 1,-857.0,0.0,-492.0,-553.0,NaN,0.0,112500.0,0.0,0.0,0.0,Consumer credit,-155.0,0.0,C,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
110,100001,Closed,currency 1,-1572.0,0.0,-1329.0,-1328.0,NaN,0.0,85500.0,0.0,0.0,0.0,Consumer credit,-155.0,0.0,C,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
111,100001,Closed,currency 1,-1572.0,0.0,-1329.0,-1328.0,NaN,0.0,85500.0,0.0,0.0,0.0,Consumer credit,-155.0,0.0,C,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
112,100001,Closed,currency 1,-1572.0,0.0,-1329.0,-1328.0,NaN,0.0,85500.0,0.0,0.0,0.0,Consumer credit,-155.0,0.0,C,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113,100001,Closed,currency 1,-1572.0,0.0,-1329.0,-1328.0,NaN,0.0,85500.0,0.0,0.0,0.0,Consumer credit,-155.0,0.0,C,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
bureau_2 = bureau_2.drop('SK_ID_BUREAU', axis=1)

In [18]:
application_test_4 = application_test_2.merge(bureau_2, how='left', on='SK_ID_CURR')

In [19]:
application_test_4.shape

(192035, 234)

In [29]:
application_test_4.sort_values('SK_ID_CURR').head(10)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY_x,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,...,MONTHS_BALANCE_-49,MONTHS_BALANCE_-48,MONTHS_BALANCE_-47,MONTHS_BALANCE_-46,MONTHS_BALANCE_-45,MONTHS_BALANCE_-44,MONTHS_BALANCE_-43,MONTHS_BALANCE_-42,MONTHS_BALANCE_-41,MONTHS_BALANCE_-40,MONTHS_BALANCE_-39,MONTHS_BALANCE_-38,MONTHS_BALANCE_-37,MONTHS_BALANCE_-36,MONTHS_BALANCE_-35,MONTHS_BALANCE_-34,MONTHS_BALANCE_-33,MONTHS_BALANCE_-32,MONTHS_BALANCE_-31,MONTHS_BALANCE_-30,MONTHS_BALANCE_-29,MONTHS_BALANCE_-28,MONTHS_BALANCE_-27,MONTHS_BALANCE_-26,MONTHS_BALANCE_-25,MONTHS_BALANCE_-24,MONTHS_BALANCE_-23,MONTHS_BALANCE_-22,MONTHS_BALANCE_-21,MONTHS_BALANCE_-20,MONTHS_BALANCE_-19,MONTHS_BALANCE_-18,MONTHS_BALANCE_-17,MONTHS_BALANCE_-16,MONTHS_BALANCE_-15,MONTHS_BALANCE_-14,MONTHS_BALANCE_-13,MONTHS_BALANCE_-12,MONTHS_BALANCE_-11,MONTHS_BALANCE_-10,MONTHS_BALANCE_-9,MONTHS_BALANCE_-8,MONTHS_BALANCE_-7,MONTHS_BALANCE_-6,MONTHS_BALANCE_-5,MONTHS_BALANCE_-4,MONTHS_BALANCE_-3,MONTHS_BALANCE_-2,MONTHS_BALANCE_-1,MONTHS_BALANCE_0
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.01885,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.15952,0.066,0.059,0.9732,NaN,NaN,NaN,0.1379,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
110,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.01885,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.15952,0.066,0.059,0.9732,NaN,NaN,NaN,0.1379,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
111,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.01885,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.15952,0.066,0.059,0.9732,NaN,NaN,NaN,0.1379,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
112,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.01885,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.15952,0.066,0.059,0.9732,NaN,NaN,NaN,0.1379,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
113,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.01885,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.15952,0.066,0.059,0.9732,NaN,NaN,NaN,0.1379,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
114,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.01885,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.15952,0.066,0.059,0.9732,NaN,NaN,NaN,0.1379,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
115,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.01885,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.15952,0.066,0.059,0.9732,NaN,NaN,NaN,0.1379,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
116,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.01885,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.15952,0.066,0.059,0.9732,NaN,NaN,NaN,0.1379,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
117,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.01885,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.15952,0.066,0.059,0.9732,NaN,NaN,NaN,0.1379,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
118,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.01885,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.15952,0.066,0.059,0.9732,NaN,NaN,NaN,0.1379,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
bureau_balance.shape

(27299925, 3)

In [34]:
bureau_balance['MONTHS_BALANCE'].unique()

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25,
       -26, -27, -28, -29, -30, -31, -32, -33, -34, -35, -36, -37, -38,
       -39, -40, -41, -42, -43, -44, -45, -46, -47, -48, -49, -50, -51,
       -52, -53, -54, -55, -56, -57, -58, -59, -60, -61, -62, -63, -64,
       -65, -66, -67, -68, -69, -70, -71, -72, -73, -74, -75, -76, -77,
       -78, -79, -80, -81, -82, -83, -84, -85, -86, -87, -88, -89, -90,
       -91, -92, -93, -94, -95, -96], dtype=int64)

In [60]:
bureau_balance['STATUS'].unique()

array(['0', 'X', 'C', '1', '5', '2', '3', '4'], dtype=object)

In [58]:
bureau_balance = bureau_balance.sort_values('MONTHS_BALANCE')
bureau_balance

          SK_ID_BUREAU  MONTHS_BALANCE STATUS
5990242        6531123             -96      0
4777049        6312611             -96      0
10202219       6396808             -96      X
14700463       6451044             -96      0
26504047       5987623             -96      0
...                ...             ...    ...
15066759       6772206               0      C
26872128       6698176               0      C
10785789       5970838               0      0
12962919       6051409               0      C
0              5715448               0      C

[27299925 rows x 3 columns]

In [52]:
bureau_balance.head(3)

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C

In [22]:
a = pd.get_dummies(bureau_balance, columns=['MONTHS_BALANCE'])

In [6]:
a.head(3)

,SK_ID_BUREAU,STATUS,MONTHS_BALANCE_-96,MONTHS_BALANCE_-95,MONTHS_BALANCE_-94,MONTHS_BALANCE_-93,MONTHS_BALANCE_-92,MONTHS_BALANCE_-91,MONTHS_BALANCE_-90,MONTHS_BALANCE_-89,MONTHS_BALANCE_-88,MONTHS_BALANCE_-87,MONTHS_BALANCE_-86,MONTHS_BALANCE_-85,MONTHS_BALANCE_-84,MONTHS_BALANCE_-83,MONTHS_BALANCE_-82,MONTHS_BALANCE_-81,MONTHS_BALANCE_-80,MONTHS_BALANCE_-79,MONTHS_BALANCE_-78,MONTHS_BALANCE_-77,MONTHS_BALANCE_-76,MONTHS_BALANCE_-75,MONTHS_BALANCE_-74,MONTHS_BALANCE_-73,MONTHS_BALANCE_-72,MONTHS_BALANCE_-71,MONTHS_BALANCE_-70,MONTHS_BALANCE_-69,MONTHS_BALANCE_-68,MONTHS_BALANCE_-67,MONTHS_BALANCE_-66,MONTHS_BALANCE_-65,MONTHS_BALANCE_-64,MONTHS_BALANCE_-63,MONTHS_BALANCE_-62,MONTHS_BALANCE_-61,MONTHS_BALANCE_-60,MONTHS_BALANCE_-59,MONTHS_BALANCE_-58,MONTHS_BALANCE_-57,MONTHS_BALANCE_-56,MONTHS_BALANCE_-55,MONTHS_BALANCE_-54,MONTHS_BALANCE_-53,MONTHS_BALANCE_-52,MONTHS_BALANCE_-51,MONTHS_BALANCE_-50,MONTHS_BALANCE_-49,MONTHS_BALANCE_-48,MONTHS_BALANCE_-47,MONTHS_BALANCE_-46,MONTHS_BALANCE_-45,MONTHS_BALANCE_-44,MONTHS_BALANCE_-43,MONTHS_BALANCE_-42,MONTHS_BALANCE_-41,MONTHS_BALANCE_-40,MONTHS_BALANCE_-39,MONTHS_BALANCE_-38,MONTHS_BALANCE_-37,MONTHS_BALANCE_-36,MONTHS_BALANCE_-35,MONTHS_BALANCE_-34,MONTHS_BALANCE_-33,MONTHS_BALANCE_-32,MONTHS_BALANCE_-31,MONTHS_BALANCE_-30,MONTHS_BALANCE_-29,MONTHS_BALANCE_-28,MONTHS_BALANCE_-27,MONTHS_BALANCE_-26,MONTHS_BALANCE_-25,MONTHS_BALANCE_-24,MONTHS_BALANCE_-23,MONTHS_BALANCE_-22,MONTHS_BALANCE_-21,MONTHS_BALANCE_-20,MONTHS_BALANCE_-19,MONTHS_BALANCE_-18,MONTHS_BALANCE_-17,MONTHS_BALANCE_-16,MONTHS_BALANCE_-15,MONTHS_BALANCE_-14,MONTHS_BALANCE_-13,MONTHS_BALANCE_-12,MONTHS_BALANCE_-11,MONTHS_BALANCE_-10,MONTHS_BALANCE_-9,MONTHS_BALANCE_-8,MONTHS_BALANCE_-7,MONTHS_BALANCE_-6,MONTHS_BALANCE_-5,MONTHS_BALANCE_-4,MONTHS_BALANCE_-3,MONTHS_BALANCE_-2,MONTHS_BALANCE_-1,MONTHS_BALANCE_0
0,5715448,C,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,5715448,C,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,5715448,C,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [23]:
a.shape

(27299925, 99)

In [26]:
bureau_2 = bureau.merge(a, how='left', on='SK_ID_BUREAU')

MemoryError: Unable to allocate 18.2 GiB for an array with shape (97, 25121815) and data type object

In [15]:
bureau_2.shape

(18955, 114)

In [16]:
bureau_2.head(5)

,SK_ID_CURR,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,STATUS,MONTHS_BALANCE_-96,MONTHS_BALANCE_-95,MONTHS_BALANCE_-94,MONTHS_BALANCE_-93,MONTHS_BALANCE_-92,MONTHS_BALANCE_-91,MONTHS_BALANCE_-90,MONTHS_BALANCE_-89,MONTHS_BALANCE_-88,MONTHS_BALANCE_-87,MONTHS_BALANCE_-86,MONTHS_BALANCE_-85,MONTHS_BALANCE_-84,MONTHS_BALANCE_-83,MONTHS_BALANCE_-82,MONTHS_BALANCE_-81,MONTHS_BALANCE_-80,MONTHS_BALANCE_-79,MONTHS_BALANCE_-78,MONTHS_BALANCE_-77,MONTHS_BALANCE_-76,MONTHS_BALANCE_-75,MONTHS_BALANCE_-74,MONTHS_BALANCE_-73,MONTHS_BALANCE_-72,MONTHS_BALANCE_-71,MONTHS_BALANCE_-70,MONTHS_BALANCE_-69,MONTHS_BALANCE_-68,MONTHS_BALANCE_-67,MONTHS_BALANCE_-66,MONTHS_BALANCE_-65,MONTHS_BALANCE_-64,...,MONTHS_BALANCE_-49,MONTHS_BALANCE_-48,MONTHS_BALANCE_-47,MONTHS_BALANCE_-46,MONTHS_BALANCE_-45,MONTHS_BALANCE_-44,MONTHS_BALANCE_-43,MONTHS_BALANCE_-42,MONTHS_BALANCE_-41,MONTHS_BALANCE_-40,MONTHS_BALANCE_-39,MONTHS_BALANCE_-38,MONTHS_BALANCE_-37,MONTHS_BALANCE_-36,MONTHS_BALANCE_-35,MONTHS_BALANCE_-34,MONTHS_BALANCE_-33,MONTHS_BALANCE_-32,MONTHS_BALANCE_-31,MONTHS_BALANCE_-30,MONTHS_BALANCE_-29,MONTHS_BALANCE_-28,MONTHS_BALANCE_-27,MONTHS_BALANCE_-26,MONTHS_BALANCE_-25,MONTHS_BALANCE_-24,MONTHS_BALANCE_-23,MONTHS_BALANCE_-22,MONTHS_BALANCE_-21,MONTHS_BALANCE_-20,MONTHS_BALANCE_-19,MONTHS_BALANCE_-18,MONTHS_BALANCE_-17,MONTHS_BALANCE_-16,MONTHS_BALANCE_-15,MONTHS_BALANCE_-14,MONTHS_BALANCE_-13,MONTHS_BALANCE_-12,MONTHS_BALANCE_-11,MONTHS_BALANCE_-10,MONTHS_BALANCE_-9,MONTHS_BALANCE_-8,MONTHS_BALANCE_-7,MONTHS_BALANCE_-6,MONTHS_BALANCE_-5,MONTHS_BALANCE_-4,MONTHS_BALANCE_-3,MONTHS_BALANCE_-2,MONTHS_BALANCE_-1,MONTHS_BALANCE_0
0,215354,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,215354,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,215354,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,215354,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,215354,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
bureau.shape

(1716428, 17)

In [25]:
bureau.head(5)

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [13]:
bureau_2 = bureau_2.drop('SK_ID_BUREAU',axis=1)

In [17]:
application_train_2 = application_train.merge(bureau_2, how='left', on='SK_ID_CURR')

In [18]:
application_train_2.shape

(10233, 235)

In [19]:
application_train_2.head(4)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY_x,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,...,MONTHS_BALANCE_-49,MONTHS_BALANCE_-48,MONTHS_BALANCE_-47,MONTHS_BALANCE_-46,MONTHS_BALANCE_-45,MONTHS_BALANCE_-44,MONTHS_BALANCE_-43,MONTHS_BALANCE_-42,MONTHS_BALANCE_-41,MONTHS_BALANCE_-40,MONTHS_BALANCE_-39,MONTHS_BALANCE_-38,MONTHS_BALANCE_-37,MONTHS_BALANCE_-36,MONTHS_BALANCE_-35,MONTHS_BALANCE_-34,MONTHS_BALANCE_-33,MONTHS_BALANCE_-32,MONTHS_BALANCE_-31,MONTHS_BALANCE_-30,MONTHS_BALANCE_-29,MONTHS_BALANCE_-28,MONTHS_BALANCE_-27,MONTHS_BALANCE_-26,MONTHS_BALANCE_-25,MONTHS_BALANCE_-24,MONTHS_BALANCE_-23,MONTHS_BALANCE_-22,MONTHS_BALANCE_-21,MONTHS_BALANCE_-20,MONTHS_BALANCE_-19,MONTHS_BALANCE_-18,MONTHS_BALANCE_-17,MONTHS_BALANCE_-16,MONTHS_BALANCE_-15,MONTHS_BALANCE_-14,MONTHS_BALANCE_-13,MONTHS_BALANCE_-12,MONTHS_BALANCE_-11,MONTHS_BALANCE_-10,MONTHS_BALANCE_-9,MONTHS_BALANCE_-8,MONTHS_BALANCE_-7,MONTHS_BALANCE_-6,MONTHS_BALANCE_-5,MONTHS_BALANCE_-4,MONTHS_BALANCE_-3,MONTHS_BALANCE_-2,MONTHS_BALANCE_-1,MONTHS_BALANCE_0
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
application_train.head(2)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,...,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,...,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,...,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
credit_card_balance.head(3)

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,1800.0,1800.0,0.000,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,2250.0,2250.0,60175.080,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,2250.0,2250.0,26926.425,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0

In [16]:
installments_payments.head(3)

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.0,6,-1180.0,-1187.0,6948.360,6948.360
1,1330831,151639,0.0,34,-2156.0,-2156.0,1716.525,1716.525
2,2085231,193053,2.0,1,-63.0,-63.0,25425.000,25425.000

In [18]:
POS_CASH_balance.head(3)

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0

In [20]:
previous_application.head(3)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,Y,1,0.0,0.182832,0.867336,XAP,Approved,-73,Cash through the bank,XAP,NaN,Repeater,Mobile,POS,XNA,Country-wide,35,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-164,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Contact center,-1,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-301,Cash through the bank,XAP,"Spouse, partner",Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0